// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Ontario.Models;

#nullable disable

namespace Project.Ontario.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230729182427_initial-migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Ontario.Models.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostOfTask")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDevelopers")
                        .HasColumnType("int");

                    b.Property<string>("TaskCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40fa08df-dbe2-4da8-baaf-86737bd3fb4e"),
                            CostOfTask = 25m,
                            Description = "Download and Install Microsoft SQL Server Server Manager from Microsoft.com",
                            EstimatedTime = 30,
                            NumberOfDevelopers = 1,
                            TaskCategory = "Back-End Development",
                            TaskName = "Install Microsoft SQL Server"
                        },
                        new
                        {
                            Id = new Guid("b0b141b1-8ee7-4d1b-9703-077ea4f29dcb"),
                            CostOfTask = 22m,
                            Description = "Use Command-Line to intialize Mudblazor Components",
                            EstimatedTime = 10,
                            NumberOfDevelopers = 2,
                            TaskCategory = "Front-End Development",
                            TaskName = "Inject MudBlazor Components"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
